name: basic-ci

on: push

jobs:
  linux:
    runs-on: ubuntu-latest
    container: swift:5.5-focal
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build

  macos:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build
